<?php
$title = 'SMS & Email';
$this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('submissions', array('action'=>'addcustomer'));?>">Add new Customer</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>Age</th>
     <th>Phone</th>
     <th>Email</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($customers as $customer) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($customer->name);?></td>
     <td><?php echo $this->escapeHtml($customer->age);?></td>
     <td><?php echo $this->escapeHtml($customer->phone);?></td>
     <td><?php echo $this->escapeHtml($customer->email);?></td>
     <td>
         <a href="<?php echo $this->url('submissions',
             array('action'=>'edit', 'id' => $customer->id));?>">Edit</a>
         <a href="<?php echo $this->url('submissions',
             array('action'=>'delete', 'id' => $customer->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>